# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('speakers', models.TextField(blank=True, help_text='Leave blank if not relevant. Write one name per line.')),
                ('location', models.TextField()),
                ('mappable_location', models.CharField(blank=True, help_text='This address will be used to calculate latitude and longitude. Leave blank and set Latitude and Longitude to specify the location yourself, or leave all three blank to auto-fill from the Location field.', max_length=128)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, help_text='Calculated automatically if mappable location is set.', max_digits=10, null=True, verbose_name='Latitude')),
                ('lon', models.DecimalField(blank=True, decimal_places=7, help_text='Calculated automatically if mappable location is set.', max_digits=10, null=True, verbose_name='Longitude')),
                ('rsvp', models.TextField(blank=True, help_text='RSVP information. Leave blank if not relevant. Emails will be converted into links.')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Event',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='EventContainer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('hide_children', models.BooleanField(default=True, verbose_name='Hide events in this container from navigation')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Event Container',
            },
            bases=('pages.page',),
        ),
    ]
